# Generated by Django 3.2.4 on 2021-07-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Inventory',
            field=models.IntegerField(default=1),
        ),
    ]
