# Generated by Django 3.2.4 on 2021-07-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='In_inventory',
            field=models.BooleanField(default=True),
        ),
    ]
